//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acepta_Metodo_De_Pago
    {
        public int Est_id { get; set; }
        public int Metodo_Pago_id { get; set; }
        public Nullable<System.DateTime> AMP_Desde { get; set; }
        public Nullable<System.DateTime> AMP_Hasta { get; set; }
    
        public virtual Estacionamiento Estacionamiento { get; set; }
        public virtual Metodos_De_Pago Metodos_De_Pago { get; set; }
    }
}
