//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacionamiento()
        {
            this.Playero = new HashSet<Playero>();
            this.Plaza = new HashSet<Plaza>();
        }
    
        public int Est_id { get; set; }
        public Nullable<int> Dueño_Legajo { get; set; }
        public string Est_nombre { get; set; }
        public string Est_provincia { get; set; }
        public string Est_localidad { get; set; }
        public string Est_direccion { get; set; }
        public string Est_horario { get; set; }
        public double Est_puntaje { get; set; }
    
        public virtual Dueño Dueño { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playero> Playero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plaza> Plaza { get; set; }
    }
}
