//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public int Playero_legajo { get; set; }
        public System.DateTime Inci_fecha_Hora { get; set; }
        public string Inci_descripcion { get; set; }
        public string Inci_Motivo { get; set; }
    
        public virtual Playero Playero { get; set; }
    }
}
