//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metodos_De_Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metodos_De_Pago()
        {
            this.Acepta_Metodo_De_Pago = new HashSet<Acepta_Metodo_De_Pago>();
            this.Pago_Ocupacion = new HashSet<Pago_Ocupacion>();
        }
    
        public int Metodo_pago_id { get; set; }
        public string Metodo_pago_descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acepta_Metodo_De_Pago> Acepta_Metodo_De_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_Ocupacion> Pago_Ocupacion { get; set; }
    }
}
