//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos_Abonados
    {
        public int PA_id { get; set; }
        public int Est_id { get; set; }
        public int Plaza_id { get; set; }
        public long TAB_Cuil_Cuit { get; set; }
        public System.DateTime TAB_Fecha_Desde { get; set; }
        public int Metodo_Pago_id { get; set; }
        public double PA_Monto { get; set; }
    
        public virtual Abono Abono { get; set; }
        public virtual Acepta_Metodo_De_Pago Acepta_Metodo_De_Pago { get; set; }
    }
}
