//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_Ocupacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago_Ocupacion()
        {
            this.Ocupacion = new HashSet<Ocupacion>();
        }
    
        public int Pago_id { get; set; }
        public int Est_id { get; set; }
        public int Metodo_Pago_id { get; set; }
        public double Pago_Importe { get; set; }
        public Nullable<System.DateTime> Pago_Fecha { get; set; }
    
        public virtual Estacionamiento Estacionamiento { get; set; }
        public virtual Metodos_De_Pago Metodos_De_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacion> Ocupacion { get; set; }
    }
}
