//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plaza()
        {
            this.Abono = new HashSet<Abono>();
            this.Ocupacion = new HashSet<Ocupacion>();
        }
    
        public int Est_id { get; set; }
        public int Plaza_id { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public string Plaza_Nombre { get; set; }
        public string Plaza_Tipo { get; set; }
        public bool Plaza_Disponibilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abono> Abono { get; set; }
        public virtual Categoria_Vehiculo Categoria_Vehiculo { get; set; }
        public virtual Estacionamiento Estacionamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacion> Ocupacion { get; set; }
    }
}
