//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarifa()
        {
            this.Ocupacion = new HashSet<Ocupacion>();
            this.Vehiculo_Abonado = new HashSet<Vehiculo_Abonado>();
        }
    
        public int Tarifa_id { get; set; }
        public Nullable<int> Est_id { get; set; }
        public Nullable<int> Tipos_Tarifa_Id { get; set; }
        public Nullable<int> Categoria_id { get; set; }
        public double Tarifa_Monto { get; set; }
        public System.DateTime Tarifa_Desde { get; set; }
    
        public virtual Categoria_Vehiculo Categoria_Vehiculo { get; set; }
        public virtual Estacionamiento Estacionamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacion> Ocupacion { get; set; }
        public virtual Tipos_Tarifa Tipos_Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo_Abonado> Vehiculo_Abonado { get; set; }
    }
}
