//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titular_Abono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titular_Abono()
        {
            this.Abono = new HashSet<Abono>();
        }
    
        public long Numero_Identificacion { get; set; }
        public System.DateTime TAB_Fecha_Desde { get; set; }
        public System.DateTime TAB_Fecha_Vto { get; set; }
        public string TAB_Nombre { get; set; }
        public string TAB_Apellido { get; set; }
        public int TAB_Telefono { get; set; }
        public string Tipo_Identificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abono> Abono { get; set; }
    }
}
