//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno()
        {
            this.Pago_Ocupacion = new HashSet<Pago_Ocupacion>();
            this.Pagos_Abonados = new HashSet<Pagos_Abonados>();
        }
    
        public System.DateTime Turno_FechaHora_Inicio { get; set; }
        public int Turno_id { get; set; }
        public int Playero_Legajo { get; set; }
        public Nullable<System.DateTime> Turno_FechaHora_fin { get; set; }
        public Nullable<double> Caja_Monto_Inicio { get; set; }
        public Nullable<double> Caja_Monto_fin { get; set; }
        public Nullable<double> Caja_Monto_total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago_Ocupacion> Pago_Ocupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos_Abonados> Pagos_Abonados { get; set; }
        public virtual Playero Playero { get; set; }
    }
}
