//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public System.DateTime Turno_FechaHora_Inicio { get; set; }
        public int Turno_id { get; set; }
        public int Playero_Legajo { get; set; }
        public Nullable<System.DateTime> Turno_FechaHora_fin { get; set; }
        public Nullable<double> Caja_Monto_Inicio { get; set; }
        public Nullable<double> Caja_Monto_fin { get; set; }
        public Nullable<double> Caja_Monto_total { get; set; }
    
        public virtual Playero Playero { get; set; }
    }
}
