//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Usu_legajo { get; set; }
        public Nullable<int> Usu_dni { get; set; }
        public string Usu_pass { get; set; }
        public string Usu_ap { get; set; }
        public string Usu_nom { get; set; }
        public string Usu_tipo { get; set; }
    
        public virtual Dueño Dueño { get; set; }
        public virtual Playero Playero { get; set; }
    }
}
