//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo_Abonado
    {
        public int VA_id { get; set; }
        public string Vehiculo_Patente { get; set; }
        public int Tarifa_id { get; set; }
        public int Est_id { get; set; }
        public int Plaza_id { get; set; }
        public long Numero_Identificacion { get; set; }
        public System.DateTime TAB_Fecha_Desde { get; set; }
        public string Tipo_Identificacion { get; set; }
    
        public virtual Abono Abono { get; set; }
        public virtual Tarifa Tarifa { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
