//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Ocupacion = new HashSet<Ocupacion>();
            this.Vehiculo_Abonado = new HashSet<Vehiculo_Abonado>();
        }
    
        public string Vehiculo_Patente { get; set; }
        public int Categoria_id { get; set; }
        public string Vehiculo_Marca { get; set; }
        public Nullable<int> Vehiculo_Modelo { get; set; }
        public string Vehiculo_Color { get; set; }
    
        public virtual Categoria_Vehiculo Categoria_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacion> Ocupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo_Abonado> Vehiculo_Abonado { get; set; }
    }
}
